"""
Course  : CMPSC 131, Fall 2024
File    : final_project.py 
Name    : Deep Patel

GitHub User:   DeepPatel-2006

Collaboration Statement: YOUR_STATEMENT_HERE
"""
import random
# Error code constants
ERROR_DUPLICATE_USER = 0
ERROR_FAILED_AUTHENTICATION = 1
ERROR_FRIEND_ALREADY_FOUND = 2
ERROR_FRIEND_NOT_FOUND = 3
ERROR_USER_NOT_FOUND = 4
ERROR_MESSAGE = {ERROR_DUPLICATE_USER: "ERROR: found duplicate user.", 
                ERROR_FAILED_AUTHENTICATION: "ERROR: authentication failed.", 
                ERROR_FRIEND_ALREADY_FOUND: "ERROR: friendship already exists.", 
                ERROR_FRIEND_NOT_FOUND: "ERROR: friendship does not exist.", 
                ERROR_USER_NOT_FOUND: "ERROR: user does not exist in the social network."}
    

def error_to_string(error_code: int) -> str:
    """
        Provides a descriptive error message

        Args:
            error_code (int): error code generated by a function
        
        Returns:
            (str) Explanation of the error code
    """
    if error_code in ERROR_MESSAGE:
        return ERROR_MESSAGE[error_code]
    else:
        return "INVALID ERROR CODE"

##################################################################################################################################

#- YOUR CODE STARTS HERE  (TODO) 


def generate_key() -> int:
    """
        generates a key using the seed

        Args:
            None
        
        Returns:
            (int) returns the output of seed 131 which is 11
    """

    random.seed(131)
    key = random.randint(1, 26)

    return key


def encrypt_password(password: str) -> str:
    """
        encrypts a password using caeser cipher method

        Args:
            password (str): the plain text password
        
        Returns:
            final_password (str): the encrypted password
    """
    assert type(password) == str 

    initial_valid_value = 33
    final_valid_value = 126
    shift = generate_key()
    final_password = ''
    for letter in password:
        initial_ascii_num = ord(letter)
        final_ascii_num = initial_ascii_num + shift

        if final_ascii_num > 126:
            final_ascii_num = initial_valid_value + (final_ascii_num - final_valid_value - 1)

        letter = chr(final_ascii_num)

        final_password += letter


    return final_password 


def list_strip(lst: list) -> list:
    """
        returns the list but with each element stipped of unnecessary spaces before or after it

        Args:
            lst (list): the input list given
        
        Returns:
            stripped_lst (lst): the input list but each element is stripped
    """
    assert type(lst) == list

    stripped_lst = []

    for item in lst:
        item = item.strip()
        stripped_lst.append(item)

    return stripped_lst

def string_to_user(txt: str) -> tuple:
    """
        turns a string that contains formatted use information into a tuple where the first element is the username and 
        the second element is a dictionary that contains the users information

        Args:
            txt (str): the formatted user information
        
        Returns:
            (tuple): the tuple that contains formatted use information into a tuple where the first element is the username and 
            the second element is a dictionary that contains the users information
    """
    assert type(txt) == str

    final_dict = {}
    txt_list = txt.split('|')

    name_pass_bio = txt_list[0]
    name_pass__bio_list = name_pass_bio.split(',')
    name_pass__bio_list = list_strip(name_pass__bio_list)

    friends = txt_list[1]
    friends_list = friends.split(',')
    friends_list = list_strip(friends_list)

    name = name_pass__bio_list[0]
    password = name_pass__bio_list[1]
    bio = name_pass__bio_list[2]
    country = name_pass__bio_list[3]

    password_encrypted = encrypt_password(password)

    final_dict['password'] = password_encrypted
    final_dict['bio'] = bio
    final_dict['country'] = country
    final_dict['friends'] = friends_list


    return (name, final_dict)


def initialize_social_network_from_file(file_name: str) -> dict | int:
    """
        turns a given file into a dictionary that contains the user's information

        Args:
            file_name (str): the name of the file that contains the formatted user information
        
        Returns:
            final_dict(dict): the dictionary that contains the user's information
    """
    assert type(file_name) == str

    final_dict = {}
    file = open(file_name, 'r')
    output_list = file.readlines()
    file.close
    user_list = []
    for line in output_list:
        output_tuple = string_to_user(line)
        name = output_tuple[0]
        
        info_dict = output_tuple[1]
        final_dict[name] = info_dict

        if name in user_list:
            print(error_to_string(ERROR_DUPLICATE_USER))
            return 0
        user_list.append(name)

    return final_dict


def authenticate_user(username: str, password: str, social_dict: dict) -> bool:
    """
        authenticates a user based on their username and password

        Args:
            username (str): the input username
            password (str): the input password
            social_dict (str): the input dictionary
        
        Returns:
            (bool): returns true if the input information matches the information in the file, and false if the user input information does
            not match the information in the file
    """
    assert type(username) == str
    assert type(password) == str
    assert type(social_dict) == dict

    if username not in social_dict:
        return False
    if encrypt_password(password) != social_dict[username]['password']:
        return False
    
    
    return True



def add_friend(self_user: str, self_pass: str, friend_user: str, social_dict: dict):
    """
        adds a friend to the users friend list

        Args:
            self_user (str): the username of the person who is adding a friend
            self_pass (str): the password of the user
            friend_user (str): the username of the friend that will be added
            social_dict (dict): the input dictionary
        
        Returns:
            None
    """
    assert type(self_user) == str
    assert type(self_pass) == str
    assert type(friend_user) == str
    assert type(social_dict) == dict

    if authenticate_user(self_user, self_pass, social_dict) == False:
        print(error_to_string(ERROR_FAILED_AUTHENTICATION))
        return ERROR_FAILED_AUTHENTICATION
    
    if friend_user in social_dict[self_user]['friends']:
        print(error_to_string(ERROR_FRIEND_ALREADY_FOUND))
        return ERROR_FRIEND_ALREADY_FOUND
    
    if friend_user not in social_dict:
        print(error_to_string(ERROR_USER_NOT_FOUND))
        return ERROR_USER_NOT_FOUND
    
    if self_user == friend_user:
        return None

    social_dict[self_user]['friends'].append(friend_user) 
    social_dict[friend_user]['friends'].append(self_user)




def get_friend_index(self_user: str, friend_user: str, social_dict: dict) -> int:
    """
        gets the index value of a friend in the user's friend list

        Args:
            self_user (str): the input username
            friend_user (str): the username of the friend
            social_dict (str): the input dictionary
        
        Returns:
            friend_index (int): the index value of the friend in the user's friend list
    """
    assert type(self_user) == str
    assert type(friend_user) == str
    assert type(social_dict) == dict

    if friend_user not in social_dict[self_user]['friends']:
        return -1
    
    friend_list = social_dict[self_user]['friends']
    
    
    for i in range(len(friend_list)):
        if friend_user == friend_list[i]:
            friend_index = i
    
    return friend_index



def remove_friend(self_user: str, self_pass: str, friend_user: str, social_dict: dict):
    """
        removes a friend to the users friend list

        Args:
            self_user (str): the username of the person who is removing a friend
            self_pass (str): the password of the user
            friend_user (str): the username of the friend that will be removed
            social_dict (dict): the input dictionary
        
        Returns:
            None
    """
    assert type(self_user) == str
    assert type(self_pass) == str
    assert type(friend_user) == str
    assert type(social_dict) == dict

    if authenticate_user(self_user, self_pass, social_dict) == False:
        print(error_to_string(ERROR_FAILED_AUTHENTICATION))
        return ERROR_FAILED_AUTHENTICATION
    
    if friend_user not in social_dict[self_user]['friends']:
        print(error_to_string(ERROR_FRIEND_NOT_FOUND))
        return ERROR_FRIEND_NOT_FOUND
    
    self_list_index = get_friend_index(self_user, friend_user, social_dict)
    friend_list_index = get_friend_index(friend_user, self_user, social_dict)

    del social_dict[self_user]['friends'][self_list_index]
    del social_dict[friend_user]['friends'][friend_list_index]



def get_user_country(user: str, social_dict: dict) -> str:
    """
        returns the country of a given user

        Args:
            user (str): the username of the user
            social_dict (dict): the input dictionary
        
        Returns:
            (str) the country of the input user
    """
    assert type(user) == str
    assert type(social_dict) == dict

    return social_dict[user]['country']


def get_countries(self_user: str, social_dict: dict) -> dict:
    """
        returns the freuquence of the countries of a user's friend list

        Args:
            self_user (str): the username of the input user
            social_dict (dict): the input dictionary
        
        Returns:
            countries_dict (dict): the dictionary which keys of countries and values of the frequency at which the countries appead in a user's friend list
    """
    assert type(self_user) == str
    assert type(social_dict) == dict

    countries_dict = {}
    friends_list = social_dict[self_user]['friends']
    for friend in friends_list:

        country = get_user_country(friend, social_dict)

        if country not in countries_dict:
            countries_dict[country] = 1
        else:
            countries_dict[country] += 1

    return countries_dict



def num_countries_in_friends(self_user: str, self_pass: str, social_dict: dict) -> dict | int:
    """
        returns the freuquence of the countries of a user's friend list

        Args:
            self_user (str): the username of the input user
            self_pass (str): the password of the input user
            social_dict (dict): the input dictionary
        
        Returns:
            country_dict (dict): the dictionary which keys of countries and values of the frequency at which the countries appead in a user's friend list
    """
    assert type(self_user) == str
    assert type(self_pass) == str
    assert type(social_dict) == dict

    if authenticate_user(self_user, self_pass, social_dict) == False:
        print(error_to_string(ERROR_FAILED_AUTHENTICATION))
        return ERROR_FAILED_AUTHENTICATION
    
    country_dict = get_countries(self_user, social_dict)
    
    return country_dict


def find_mutual_friend(self_user: str, friend_user: str, social_dict: dict) -> int:
    """
        returns the number of friends a given user and a friend in their friend list have

        Args:
            self_user (str): the username of the input user
            friend_user (str): a given friend in the user's friend list
            social_dict (dict): the input dictionary
        
        Returns:
            mutual_friends (int): the amount of mutual friends self_user and friend_user have
    """
    assert type(self_user) == str
    assert type(friend_user) == str
    assert type(social_dict) == dict
    
    self_friend_list = social_dict[self_user]['friends']
    friend_friend_list = social_dict[friend_user]['friends']
    mutual_friends = 0
    
    for friend in self_friend_list:
        if friend in friend_friend_list:
            mutual_friends += 1
        

    return mutual_friends


def sort_friend_list(self_user: str, self_pass: str, social_dict: dict):
    """
        sorts a given user's friend list in decending order of mututal friends between the user and each friend in their friend list

        Args:
            self_user (str): the username of the input user
            self_pass (str): the password of the input user
            social_dict (dict): the input dictionary
        
        Returns:
            None
    """
    assert type(self_user) == str
    assert type(self_pass) == str
    assert type(social_dict) == dict

    if authenticate_user(self_user, self_pass, social_dict) == False:
        print(error_to_string(ERROR_FAILED_AUTHENTICATION))
        return ERROR_FAILED_AUTHENTICATION

    friend_mutual_list = []
    for friend in social_dict[self_user]['friends']:
        mutuals = find_mutual_friend(self_user, friend, social_dict)
        friend_mutual_list.append([friend, mutuals])
    
    n = len(friend_mutual_list)
    print(friend_mutual_list)
    for i in range(n):
        for j in range(n - i - 1):
            if friend_mutual_list[j][1] < friend_mutual_list[j+1][1]:
                friend_mutual_list[j], friend_mutual_list[j+1] = friend_mutual_list[j+1], friend_mutual_list[j]
                social_dict[self_user]['friends'][j], social_dict[self_user]['friends'][j+1] = social_dict[self_user]['friends'][j+1], social_dict[self_user]['friends'][j]
                


def get_level_friends(self_user: str, self_pass: str, social_dict: dict, level: int) -> int | list:
    """
        returns a list of all the users that are a certain level of mutuality away from the given input user

        Args:
            self_user (str): the username of the input user
            self_pass (str): the password of the input user
            social_dict (dict): the input dictionary
            level (int): the given input level
        
        Returns:
            level_list (list): the list that contains all of the users in the dictionary that are a current level of mutuality away from the given input user
    """
    assert type(self_user) == str
    assert type(self_pass) == str
    assert type(social_dict) == dict
    assert type(level) == int
    
    if authenticate_user(self_user, self_pass, social_dict) == False:
        print(error_to_string(ERROR_FAILED_AUTHENTICATION))
        return ERROR_FAILED_AUTHENTICATION
    

    level_list = []
    queue = []
    distances = {}
    distances[self_user] = 0
    queue.append(self_user)
    while queue:
        current_user = queue[0]
        del queue[0]
        for friend in social_dict[current_user]['friends']:
            if friend in distances:
                if distances[friend] > (distances[current_user] + 1):
                    distances[friend] = (distances[current_user] + 1)
            else:
                queue.append(friend)
                distances[friend] = distances[current_user] + 1

    for key in distances:
        if distances[key] == level:
            level_list.append(key)


    return level_list

#- YOUR CODE ENDS HERE 
#######################################################################################################################################

def social_network_application() -> None:
    """
        Social Network Interface for testing integration from all helper functions only
    """
    user_file_path = input("Enter users file path: ")
    
    # Initialize social network
    social_network = initialize_social_network_from_file(user_file_path)
    if (type(social_network) == int):
        print(error_to_string(social_network))
    
    # Flag to keep track of login status
    user_logged_in = False
    print("Welcome to the CMPSC 131 Social Network!")
    
    # Main loop for user logged in
    while not user_logged_in:
        
        # Login credentials input
        print("Please enter your login credentials:")
        username = input("Username: ")
        password = input("Password: ")
        
        # Authenticate the user.
        user_logged_in = authenticate_user(username, password, social_network)

        if not user_logged_in:
            print("Authentication failed. Incorrect username or password.")
        else:
            print("Login Successful")
            display_menu = True
            
            # Loop for the menu. If user is logged in, they can view the menu infinitely until they log out or exit the program.
            while display_menu:
                print("\n\nPlease select from the menu: ")
                print("1. Add Friend")    
                print("2. Remove Friend")
                print("3. Display Friend List (Sorted)")
                print("4. Display nth Level Friends")
                print("5. Display countries in your network")
                print("6. Log Out")
                print("7. Display menu")
                menu_option = input("Selection: ")


                if menu_option == '1':
                    friend_username = input("Friend Username: ")
                    ret = add_friend(username, password, friend_username, social_network)
                    if ret is None:
                        sort_friend_list(username, password, social_network)
                        print(f"Updated Friend List: {social_network[username]['friends']}")
                    else:
                        print(error_to_string(ret))
                elif menu_option == '2':
                    friend_username = input("Friend Username: ")
                    ret = remove_friend(username, password, friend_username, social_network)
                    if ret is None:
                        sort_friend_list(username, password, social_network)
                        print(f"Updated Friend List: {social_network[username]['friends']}")
                    else:
                        print(error_to_string(ret))
                elif menu_option == '3':
                    sort_friend_list(username, password, social_network)
                    print(f"Updated Friend List: {social_network[username]['friends']}")
                elif menu_option == '4':
                    level = int(input("Enter friendship level (1,2,3, etc.): "))
                    print(f"Your friends at level {level} are {get_level_friends(username, password, social_network, level)}")
                elif menu_option == '5':
                    print(f"Users per country in {username}'s network: \n {num_countries_in_friends(username, password, social_network)}")
                elif menu_option == '6':
                    # Exit display menu loop
                    display_menu = False
                    # Trigger the re-execution of the login loop
                    user_logged_in = False
                elif menu_option == '7':
                    print("Returning to main menu...")
                else:
                    print("Invalid Option. Returning to main menu...")
            
            print("Logging out...")







    
def main() -> None:
    # Start application
    pass
    # social_network_application()
    

if __name__ == "__main__":
    main()
